name: Docker Build and Deploy

on:
  push:
    branches: "main" 

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Build the Docker image
        - uses: actions/checkout@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER.USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and Push Docker Image
          run: |
            docker build -t ${{ secrets.DOCKER.USERNAME}}/my-monitoring-app:latest .
            docker push ${{ secrets.DOCKER.USERNAME}}/my-monitoring-app

        - name: Deploy Docker Container
          run: |
            docker-compose up -d

        
      
